### ISSUE TITLE
没一个让人省心的，一大堆报错

### ISSUE THREAD

**Issue by hechuanhua** [vikingmute/webpack-for-fools#8]
0 info it worked if it ends with ok
1 verbose cli [ 'E:\NODE\node.exe',
1 verbose cli   'E:\NODE\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.15.1
3 info using node@v4.4.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev webpack-react-kit@1.0.0
6 info dev webpack-react-kit@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info webpack-react-kit@1.0.0 Failed to exec dev script
9 verbose stack Error: webpack-react-kit@1.0.0 dev: `webpack-dev-server`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (E:\NODE\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (E:\NODE\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid webpack-react-kit@1.0.0
11 verbose cwd D:\Program Files (x86)\XAMPP\htdocs\webpack\webpack-react-kit
12 error Windows_NT 10.0.10586
13 error argv "E:\NODE\node.exe" "E:\NODE\node_modules\npm\bin\npm-cli.js" "run" "dev"
14 error node v4.4.3
15 error npm  v2.15.1
16 error code ELIFECYCLE
17 error webpack-react-kit@1.0.0 dev: `webpack-dev-server`
17 error Exit status 1
18 error Failed at the webpack-react-kit@1.0.0 dev script 'webpack-dev-server '.
18 error This is most likely a problem with the webpack-react-kit package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dev-server
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs webpack-react-kit
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls webpack-react-kit
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

对于新手来说真是痛苦，也不知道哪里有问题

**Comment by hechuanhua** [comment]
问题找到了，我用的淘宝镜像，安装webpack 和webpack-dev-server貌似有问题，用npm重新安装一下就好了
